version: '2'
services:
  profiteer:
    build: ./
    ports:
      - 3001:80
    volumes:
      - ./application:/var/www/html
    networks:
      - dt-net
  redis:
    image: redis:alpine
    networks:
      - dt-net
  postgres:
    build: ./postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_ROOT_PASSWORD: root
      POSTGRES_DATABASE: my_app
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    volumes:
      - postgresdata:/var/lib/postgresql
    networks:
      - dt-net
networks:
  dt-net:
    driver: 'bridge'
volumes:
  postgresdata:
    driver: 'local'