version: '2'
services:
  nginx:
    build: ./nginx
    ports:
      - '${APP_PORT}:80'
    volumes:
      - ./application:/var/www/html
    networks:
      - dt-net
    environment:
      APP_ENV: ${APP_ENV}
  php:
    build: ./php
    volumes:
      - ./application:/var/www/html
      - ./application:/opt
    networks:
      - dt-net
    environment:
      APP_ENV: ${APP_ENV}
  redis:
    image: redis:alpine
    networks:
      - dt-net
  postgres:
    image: ./postgres
    ports:
      - '${APP_DB_PORT}:5432'
    environment:
      POSTGRES_ROOT_PASSWORD: root
      POSTGRES_DATABASE: my-app
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    volumes:
      - postgresdata:/var/lib/postgresql
    networks:
      - dt-net
networks:
  dt-net:
    driver: 'bridge'
volumes:
  postgresdata:
    driver: 'local'